name: docling

services:
  app:
    image: ghcr.io/docling-project/docling-serve-cu130:main
    restart: unless-stopped
    ipc: host  # Required for efficient memory sharing in multi-process inference
    ports:
      - $APP_PORT:5001
    environment:
      DOCLING_SERVE_ENABLE_UI: 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
